name: Deploy to EC2 with CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-west-2'  # 원하는 AWS 지역으로 변경

    - name: Sync to S3
      run: |
        aws s3 sync . s3://your-bucket-name --exclude ".git/*"  # S3에 배포할 파일을 업로드

    - name: Deploy to EC2 with CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name MyApplication \
          --deployment-group-name MyDeploymentGroup \
          --revision file://deployment.zip \
          --deployment-config-name CodeDeployDefault.AllAtOnce
